#数据源配置
spring:
  datasource:
    druid:
      username: root
      password: ahao123
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/fruitfresh?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
      db-type: com.alibaba.druid.pool.DruidDataSource
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 20
      time-between-eviction-runs-millis: 60000
#服务器配置
server:
  port: 8033
